### ISSUE TITLE
Possible to make a Textual app hang with a few push/pop screens

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1231]
I don't know right now that it's the push/pop of a screen that's the issue here, but while testing a question raised on Discord (which ended up being another instance of #1169 as best as I can tell -- something that's a bug in 0.4.0 but fine in `main`) I was able to make a simple Textual app outright hang with this code:

```python
from textual.app import App, ComposeResult
from textual.screen import Screen
from textual.widgets import Header, Footer, Static

class TestScreen( Screen ):

    def compose(self) -> ComposeResult:
        yield Header()
        yield Static( "This is a screen" )
        yield Static( f"The screen stack is this big: {len(self.app.screen_stack)}")
        yield Footer()

class ScreenTest( App[ None ] ):

    BINDINGS = [
        ( "n", "new_screen", "New Screen" ),
        ( "r", "remove_screen", "Remove Screen" )
    ]

    def compose(self) -> ComposeResult:
        yield Header()
        yield Static( "This the default screen" )
        yield Static( f"The screen stack is this big: {len(self.screen_stack)}")
        yield Footer()

    def action_new_screen( self ):
        self.push_screen( TestScreen() )

    def action_remove_screen( self ):
        self.pop_screen()

if __name__ == "__main__":
    ScreenTest().run()
```

I'm finding that if I add and then remove a screen around 5 times (not exactly though, as far as I can tell), the app becomes unresponsive to any key binding inputs. I can <kbd>Ctrl</kbd>+<kbd>C</kbd> out and when I do the app disappears but I don't get my shell prompt back, if I <kbd>Ctrl</kbd>+<kbd>C</kbd> again I do, with a traceback that always looks like this:

```
Traceback (most recent call last):
  File "/Users/davep/develop/python/textual/../textual-sandbox/screens-with-header.py", line 33, in <module>
    ScreenTest().run()
  File "/Users/davep/develop/python/textual/src/textual/app.py", line 862, in run
    asyncio.run(run_app())
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1863, in _run_once
    event_list = self._selector.select(timeout)
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt
```

The culprit seems to be 1f2781cd6cda94d410d45c3738ee68c52295088b -- if I run the test with the code before that commit, it all works fine and I can't reproduce this problem; if I check out the code at that commit I can reproduce the issue.

Tagging @willmcgugan.

**Comment by davep** [comment]
Fixed by e7743d306921989661b81993161ef337bd921fb9
