### ISSUE TITLE
AttributeError: 'Tabs' object has no attribute 'animation_function'

### ISSUE THREAD

**Issue by M737** [Textualize/textual#1244]
Traceback (most recent call last):
  File "/home/gbb/demo/treeDemo/tab_test.py", line 32, in <module>
    TabApp().run()
  File "/home/gbb/demo/treeDemo/tab_test.py", line 19, in __init__
    self.tabs = Tabs(list(self.keys_to_tabs.values()))
  File "/usr/local/Python-3.10.7/lib/python3.10/site-packages/textual/widgets/tabs.py", line 215, in __init__
    self._active_tab_name = active_tab or next(iter(self.tabs), None)
  File "/usr/local/Python-3.10.7/lib/python3.10/site-packages/textual/reactive.py", line 190, in __set__
    self._check_watchers(obj, name, current_value)
  File "/usr/local/Python-3.10.7/lib/python3.10/site-packages/textual/reactive.py", line 252, in _check_watchers
    require_compute = require_compute or invoke_watcher(
  File "/usr/local/Python-3.10.7/lib/python3.10/site-packages/textual/reactive.py", line 236, in invoke_watcher
    watch_result = watch_function(value)
  File "/usr/local/Python-3.10.7/lib/python3.10/site-packages/textual/widgets/tabs.py", line 319, in watch__active_tab_name
    easing=self.animation_function,
AttributeError: 'Tabs' object has no attribute 'animation_function'

my source code：

```python
class TabApp(App):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.keys_to_tabs = {
            "1": Tab("Summary", name="summary"),
            "2": Tab("Fail", name="fail"),
            "3": Tab("Pass", name="pass"),
        }
    def compose(self):
        yield Header()
        yield Container(
            Tabs(list(self.keys_to_tabs.values()))
        )
        yield Footer()
```

**Comment by davep** [comment]
Looking at your traceback, it looks like you're trying to make use of `textual.widgets.tabs`? I'm afraid that's a bit of a hangover from an earlier version of Textual, which is why it's not [one of the documented widgets](https://textual.textualize.io/widgets/), [isn't "exported" from `widgets`](https://github.com/Textualize/textual/blob/f5db48211f88b5817e0b444af19486209247e1f0/src/textual/widgets/__init__.py#L27-L42), and is actually [on the roadmap to be added in the future](https://textual.textualize.io/roadmap/#widgets).

**Comment by M737** [comment]
watch__active_tab_name,

This method  from Tabs has one more "_",  Is this the reason?

**Comment by davep** [comment]
I'm afraid I've not personally looked at the Tabs code so can't say what problems there may be, but that widget isn't supported and is incompatible with the current version of Textual. A replacement will be built in the future.

**Comment by davep** [comment]
Given the tabs code isn't currently supported, and you found a workaround that works for you, closing this.
