### ISSUE TITLE
Changing App's sub_title fails (regression from 0.4.0)

### ISSUE THREAD

**Issue by brechtm** [Textualize/textual#1275]
Since 0.5.0 (also in main), an exception is thrown when setting my App's `self.app.sub_title`:

```
Exception in callback SimulationRunnerUI._handle_task_result(True)(<Task finishe...> result=None>)
handle: <Handle SimulationRunnerUI._handle_task_result(True)(<Task finishe...> result=None>)>
Traceback (most recent call last):
  File "/apps/hosted/spack/opt/spack/linux-rhel7-haswell/gcc-4.8.5/python-3.10.1-ek76ski4ctzhij7smku7sh3bmupopkou/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/projects/Triton/users/brechtm/triton_alpha/main/tools/chipmunk/simulations/runnerui.py", line 92, in _handle_task_result
    self.app.sub_title = "BATCH COMPLETED; EXITING"
  File "/projects/Triton/users/brechtm/triton_alpha/main/.venv/lib/python3.10/site-packages/textual/reactive.py", line 190, in __set__
    self._check_watchers(obj, name, current_value)
  File "/projects/Triton/users/brechtm/triton_alpha/main/.venv/lib/python3.10/site-packages/textual/reactive.py", line 258, in _check_watchers
    require_compute = require_compute or invoke_watcher(
  File "/projects/Triton/users/brechtm/triton_alpha/main/.venv/lib/python3.10/site-packages/textual/reactive.py", line 236, in invoke_watcher
    watch_result = watch_function(value)
  File "/projects/Triton/users/brechtm/triton_alpha/main/.venv/lib/python3.10/site-packages/textual/widgets/_header.py", line 134, in set_sub_title
    self.query_one(HeaderTitle).sub_text = sub_title
  File "/projects/Triton/users/brechtm/triton_alpha/main/.venv/lib/python3.10/site-packages/textual/dom.py", line 728, in query_one
    return query.only_one() if expect_type is None else query.only_one(expect_type)
  File "/projects/Triton/users/brechtm/triton_alpha/main/.venv/lib/python3.10/site-packages/textual/css/query.py", line 245, in only_one
    the_one = self.first(expect_type) if expect_type is not None else self.first()
  File "/projects/Triton/users/brechtm/triton_alpha/main/.venv/lib/python3.10/site-packages/textual/css/query.py", line 217, in first
    raise NoMatches(f"No nodes match {self!r}")
textual.css.query.NoMatches: No nodes match <DOMQuery Header() filter='HeaderTitle'>
```

**Comment by davep** [comment]
Do you think you would be able to provide a self-contained example of this error? This code:

```python
from textual.app import App, ComposeResult
from textual.widgets import Header, Footer, Button

class HeaderTest( App[ None ] ):

    TITLE = "This is the title"
    SUB_TITLE = "This is the sub-title"

    CSS = """
    Screen {
        align: center middle;
    }
    """

    counter = 0

    def compose( self ) -> ComposeResult:
        yield Header()
        yield Button()
        yield Footer()

    def on_button_pressed( self, _: Button.Pressed ) -> None:
        self.counter += 1
        self.title = f"This is title update {self.counter}"
        self.sub_title = f"This is sub-title update {self.counter}"

if __name__ == "__main__":
    HeaderTest().run()
```

Is working fine for me with 0.5.0 and also `main` as of the time of writing.

**Comment by davep** [comment]
Wondering if, perhaps, it was in any way related to going via `self.app` in some child location in the DOM, I also just tested with this:

```python
from textual.app import App, ComposeResult
from textual.widgets import Header, Footer, Button
from textual.screen import Screen

class Main( Screen ):

    counter = 0

    def compose( self ) -> ComposeResult:
        yield Header()
        yield Button()
        yield Footer()

    def on_button_pressed( self, _: Button.Pressed ) -> None:
        self.counter += 1
        self.app.title = f"This is title update {self.counter}"
        self.app.sub_title = f"This is sub-title update {self.counter}"

class HeaderTest( App[ None ] ):

    TITLE     = "This is the title"
    SUB_TITLE = "This is the sub-title"
    CSS       = "Main { align: center middle;}"
    SCREENS   = { "main": Main }

    def on_mount( self ):
        self.push_screen( "main" )

if __name__ == "__main__":
    HeaderTest().run()
```

That still works as expected too with 0.5.0 and `main`.

**Comment by brechtm** [comment]
I was writing to App's `self.app.sub_title`. Changing that to `self.sub_title` doesn't make a difference, however.

Setting the subtitle from an event handling method works fine, but the exception is thrown when setting `sub_title` from a [done callback](https://docs.python.org/3/library/asyncio-task.html#asyncio.Task.add_done_callback) for an asyncio task (which worked pre-0.5.0).

**Comment by davep** [comment]
I have tested the above with `self.app.sub_title` from a child too and it worked fine.

Could you possibly write a small standalone example so I can see the issue better?

**Comment by willmcgugan** [comment]
Could you callback be running before the DOM is created? The earliest point you could expect the DOM to be ready is after App.on_mount

**Comment by brechtm** [comment]
> Could you callback be running before the DOM is created? The earliest point you could expect the DOM to be ready is after App.on_mount

No, I think, as the tasks were created in `on_mount` as in the code above.

**Comment by brechtm** [comment]
I was able to reproduce is a couple of times with this code, hitting 'q' shortly after starting the app:
```python
import asyncio

from textual.app import App, ComposeResult
from textual.widgets import Header, Footer, Button

class HeaderTest( App[ None ] ):

    TITLE = "This is the title"
    SUB_TITLE = "This is the sub-title"

    CSS = """
    Screen {
        align: center middle;
    }
    """
    
    BINDINGS = [
        ("q", "quit", "Quit"),
    ]

    def compose( self ) -> ComposeResult:
        yield Header()
        yield Footer()

    def on_mount(self) -> None:
        self._task = asyncio.create_task(self._relax())
        self._task.add_done_callback(self._relax_callback)
        self.sub_title = "Starting to relax..."

    async def _relax(self):
        await asyncio.sleep(2)

    def _relax_callback(self, task: asyncio.Task) -> None:
        try:
            task.result()
        except asyncio.CancelledError:
            pass
        self.sub_title = "All relaxed now!"
        self.set_timer(2, self.action_quit)

    async def action_quit(self) -> None:
        # self._task.cancel()
        await super().action_quit()


if __name__ == "__main__":
    HeaderTest().run()
```

**Comment by rodrigogiraoserrao** [comment]
So, to clarify @brechtm, the problem with your concrete example was not a Textual bug, but rather a consequence of the fact that the `self._relax_callback` was running to completion even when the original `_relax` task was cancelled because you were quitting the app?

If I understood things right, does that mean that this issue can be closed, or can you find another reproducible example where you have the original problem when setting the sub title?

**Comment by brechtm** [comment]
I don't know about the details (`_relax` and `_relax_callback`), but this was indeed due to a concurrency handling issue on my part.
