### ISSUE TITLE
Tree widget import error

### ISSUE THREAD

**Issue by elkinaguas** [Textualize/textual#1300]
Sorry if this has been discussed already. The Tree widget shows an error when is being imported. The code I used is the one in the example in the documentation (https://textual.textualize.io/widgets/tree/).

---
Output after executing the code:
```bash
Traceback (most recent call last):
  File "tree.py", line 2, in <module>
    from textual.widgets import Tree
  File "/data/textual_dev/venv/lib/python3.8/site-packages/textual/widgets/__init__.py", line 55, in __getattr__
    raise ImportError(f"Package 'textual.widgets' has no class '{widget_class}'")
ImportError: Package 'textual.widgets' has no class 'Tree'
```

**Comment by davep** [comment]
Unfortunately this is down to the docs for `main` leaking into the wild a wee bit too early (unforeseen consequence of maintaining and updating the blog from the same repo -- something we'll look to sorting). `Tree` is in `main` and can be expected in the next release of Textual.

Sorry about that.

**Comment by oleksis** [comment]
Other issue is when use `textual --version` : `ModuleNotFoundError: No module named 'click'`

```bash
➜ python -V
Python 3.10.2

➜ python -m pip install --upgrade pip

➜ pip install textual

➜ textual --version
  File "C:\temp\venv\Scripts\textual.exe\__main__.py", line 4, in <module>
  File "C:\temp\venv\lib\site-packages\textual\cli\cli.py", line 4, in <module>
    import click
ModuleNotFoundError: No module named 'click'

➜ pip install click

➜ textual --version
textual, version 0.5.0

➜ vim t.py
```

```python
# https://textual.textualize.io/widgets/tree/#__tabbed_1_2
from textual.app import App, ComposeResult
from textual.widgets import Tree


class TreeApp(App):
    def compose(self) -> ComposeResult:
        tree: Tree = Tree("Dune")
        tree.root.expand()
        characters = tree.root.add("Characters", expand=True)
        characters.add_leaf("Paul")
        characters.add_leaf("Jessica")
        characters.add_leaf("Channi")
        yield tree


if __name__ == "__main__":
    app = TreeApp()
    app.run()

```

```bash
➜ python t.py
Traceback (most recent call last):
  File "C:\temp\t.py", line 2, in <module>
    from textual.widgets import Tree
  File "C:\temp\venv\lib\site-packages\textual\widgets\__init__.py", line 55, in __getattr__
    raise ImportError(f"Package 'textual.widgets' has no class '{widget_class}'")
ImportError: Package 'textual.widgets' has no class 'Tree'

➜ pip uninstall textual

➜ pip install git+https://github.com/Textualize/textual.git@cf539293ff3b61eadb7545dae5787bbc375158da

➜ python t.py

TreeApp
▼ Dune
└── ▼ Characters
    ├── Paul
    ├── Jessica
    └── Channi
```

Compare Textual 0.5.0 from PyPI with Textual.git@cf539293ff3b61eadb7545dae5787bbc375158da
```bash
➜ diff --brief --recursive --exclude '*.pyc' ./build/textual-0.5.0@pypi ./build/textual-0.5.0@cf539293ff3b61eadb7545dae5787bbc375158da | grep 'Only in'
Only in ./build/textual-0.5.0@cf539293ff3b61eadb7545dae5787bbc375158da/widgets: _tree.py
Only in ./build/textual-0.5.0@pypi/widgets: _tree_control.py
Only in ./build/textual-0.5.0@cf539293ff3b61eadb7545dae5787bbc375158da/widgets: _tree_node.py
```

**Comment by davep** [comment]
> Other issue is when use textual --version : ModuleNotFoundError: No module named 'click'

I imagine that will be down to having installed `textual` rather than `textual[dev]`. See #983 for a bit more background. The aim at some point is that the `textual` command will be removed from the non-[dev] installation.
