### ISSUE TITLE
Handle signals to enable suspend and resume

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1582]
We need to allow ^Z to suspect a Textual app and `fg` to resume it.

To do this, I think we need to respond to the `SIGSTOP` and `SIGCONT` signals.

On `SIGSTOP` we need to exit application mode, and on `SIGCONT` we need to enter application mode and refresh the screen.

I think this is a Linux only thing. I don't think that Windows has the same concept.

The PR from @JoshKarpel may play a part in this. https://github.com/Textualize/textual/pull/1541

https://stackoverflow.com/questions/39188508/how-curses-preserves-screen-contents

**Comment by davep** [comment]
> To do this, I think we need to respond to the `SIGSTOP` and `SIGCONT` signals.
> 
> On `SIGSTOP` we need to exit application mode, and on `SIGCONT` we need to enter application mode and refresh the screen.

I suspect we may need to do this some other way. `SIGSTOP` can't be caught on either Linux or macOS. From `signal(2)` on GNU/Linux:

> The signals SIGKILL and SIGSTOP cannot be caught or ignored.

and `signal(3)` on macOS:

> Except for the SIGKILL and SIGSTOP signals, the signal() function allows for a signal to be caught, to be ignored, or to generate an interrupt

Attempting to hook `SIGSTOP` results in this on Linux or macOS:

```python
>>> signal.signal(signal.SIGSTOP,lambda _1,_2:None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
OSError: [Errno 22] Invalid argument
```

I believe it's actually `SIGTSTP` that we want here. Doing this on macOS and then pressing <kbd>Ctrl</kbd>+<kbd>Z</kbd> in the REPL has the desired effect:

```python
>>> import signal
>>> def handle( sig, stack ):
...     print( repr( ( sig, stack ) ) )
...
>>> signal.signal(signal.SIGTSTP,handle)
<Handlers.SIG_DFL: 0>
>>> (18, None)
```

Ditto on GNU/Linux.

**Comment by davep** [comment]
This also raises a question: right now <kbd>Ctrl</kbd>+<kbd>Z</kbd> is a "normal" key from a Textual point of view. A developer using Textual can hook the key and make use of it (press it in `textual keys` to see that it's processed normally). Adding this support will change that. So, the question is: should this be done as a "allow app to suspend" option? And if so, what would be an acceptable default?

**Comment by willmcgugan** [comment]
I think this is an expected feature for the most part. Suggest we enabled it with an action, with a default binding to Ctrl+Z. If a dev doesn't want suspend, they can remove the binding.

**Comment by darrenburns** [comment]
@davep Could you add a note on why this was blocked?

**Comment by davep** [comment]
Pretty much from [this comment in the linked PR on down](https://github.com/Textualize/textual/pull/1655#issuecomment-1402303535). Long story short: it all seems to work but doesn't play well with the pilot so can't have unit tests yet.
