### ISSUE TITLE
"No module named 'textual.widgets._tab'" thrown when textual.widgets.Tab is referenced

### ISSUE THREAD

**Issue by liancheng** [Textualize/textual#2044]
Was trying out the new `Tabs` widget using Python 3.10.4 and found that I couldn't use `Tabs` together with `Tab` (needed `Tab` to assign CSS IDs). This issue can be reproduced by applying the following diff to textual 0.15.0:

```diff
diff --git a/docs/examples/widgets/tabs.py b/docs/examples/widgets/tabs.py
index 675ccf38..307f44e3 100644
--- a/docs/examples/widgets/tabs.py
+++ b/docs/examples/widgets/tabs.py
@@ -1,5 +1,5 @@
 from textual.app import App, ComposeResult
-from textual.widgets import Footer, Label, Tabs
+from textual.widgets import Footer, Label, Tabs, Tab
 
 NAMES = [
     "Paul Atreidies",
@@ -40,7 +40,7 @@ class TabsApp(App):
     ]
 
     def compose(self) -> ComposeResult:
-        yield Tabs(NAMES[0])
+        yield Tabs(Tab(NAMES[0]))
         yield Label()
         yield Footer()
```

Run `python docs/examples/widgets/tabs.py`, and I got:

```
Traceback (most recent call last):
  File "/Users/lian/local/src/textual/main/docs/examples/widgets/tabs.py", line 2, in <module>
    from textual.widgets import Footer, Label, Tabs, Tab
  File "/Users/lian/.pyenv/versions/3.10.4/lib/python3.10/site-packages/textual/widgets/__init__.py", line 80, in __getattr__
    module = import_module(widget_module_path, package="textual.widgets")
  File "/Users/lian/.pyenv/versions/3.10.4/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'textual.widgets._tab'
```

**Comment by davep** [comment]
Good spot! Missing file/export in the widgets directory. Easy fix.

**Comment by davep** [comment]
The fix is in and will be in the next release (I think Will is going to do a `.1` release pretty soon).

Thanks again for flagging this up!
