### ISSUE TITLE
Need to update poetry.core requirement, use of dependency groups requires >=1.2.0

### ISSUE THREAD

**Issue by glenn-mcallister-aiven** [Textualize/textual#2562]
I was trying to create an RPM build of 0.24.1 for Fedora Core 37, as the available RPM is just way too old, based off the one for FC39 (Rawhide), which is where I hit this bug.

In `pyproject.toml` we have the following dependency group definition: 
https://github.com/Textualize/textual/blob/d266e3685f37353eb3e201a6538d28e4cc5d7025/pyproject.toml#L55-L56

That group definition requires Poetry `>=1.2.0`, however the current definition is `>=1.0.0`: https://github.com/Textualize/textual/blob/d266e3685f37353eb3e201a6538d28e4cc5d7025/pyproject.toml#L85-L87

This causes the RPM build to fail in F37 as depending on `python3-poetry` installs `1.0.8`, and then the build fails during the `buildrequires` phase as follows:

```
+ /usr/bin/python3 -Bs /usr/lib/rpm/redhat/pyproject_buildrequires.py --generate-extras --python3_pkgversion 3 --wheeldir /var/tmp/rpmbuild/BUILD/textual-0.24.1/pyproject-wheeldir --output /var/tmp/rpmbuild/BUILD/python-textual-0.24.1-1.fc37.aarch64-pyproject-buildrequires -r -x dev
Handling poetry-core>=1.0.0 from build-system.requires
Requirement satisfied: poetry-core>=1.0.0
   (installed: poetry-core 1.0.8)
Traceback (most recent call last):
  File "/usr/lib/rpm/redhat/pyproject_buildrequires.py", line 504, in main
    generate_requires(
  File "/usr/lib/rpm/redhat/pyproject_buildrequires.py", line 411, in generate_requires
    generate_run_requirements(backend, requirements, build_wheel=build_wheel, wheeldir=wheeldir)
  File "/usr/lib/rpm/redhat/pyproject_buildrequires.py", line 318, in generate_run_requirements
    generate_run_requirements_hook(backend, requirements)
  File "/usr/lib/rpm/redhat/pyproject_buildrequires.py", line 274, in generate_run_requirements_hook
    dir_basename = prepare_metadata('.')
                   ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
    poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/poetry/core/factory.py", line 43, in create_poetry
    raise RuntimeError("The Poetry configuration is invalid:\n" + message)
RuntimeError: The Poetry configuration is invalid:
  - Additional properties are not allowed ('group' was unexpected)
```

My issue in getting a working RPM in F37 aside, this should be updated.

**Comment by glenn-mcallister-aiven** [comment]
Verified PR has been included in release 0.25.0.
