### ISSUE TITLE
Trying to run examples/simple.py results in CancelledError

### ISSUE THREAD

**Issue by mwalkerr** [Textualize/textual#283]
Steps:
1. poetry shell
2. python3 examples/simple.py

UI flashes on screen for second but then the app crashes with:
```
Traceback (most recent call last):
  File "/Users/monroe/ws/textual/src/textual/_timer.py", line 92, in _run
    async def _run(self) -> None:
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/monroe/ws/textual/src/textual/app.py", line 204, in run_app
    await app.process_messages()
  File "/Users/monroe/ws/textual/src/textual/app.py", line 311, in process_messages
    await self.animator.stop()
  File "/Users/monroe/ws/textual/src/textual/_animator.py", line 119, in stop
    await self._timer.stop()
  File "/Users/monroe/ws/textual/src/textual/_timer.py", line 82, in stop
    await self._task
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/monroe/ws/textual/examples/simple.py", line 38, in <module>
    MyApp.run(title="Simple App", log="textual.log")
  File "/Users/monroe/ws/textual/src/textual/app.py", line 206, in run
    asyncio.run(run_app())
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
asyncio.exceptions.CancelledError
```
This is after cloning the repo at commit cc9c185705a4934b4d65cb2776b6a8ec302920a1

**Comment by willmcgugan** [comment]
You’ll need to run the examples from the examples directory.

**Comment by mwalkerr** [comment]
@willmcgugan Awesome, that works now! Thank you for the quick response.

Why does it need to be run in the examples directory? Seems most likely that it's due to the read of "richreadme.md"? Any idea why the exception for that wasn't shown anywhere? I haven't worked with Python in a while, so apologies if the underlying issue is actually apparent

**Comment by mwalkerr** [comment]
@willmcgugan Looking more into this, I see that the error is getting suppressed here:
```python
  try:
      await self.dispatch_message(message)
  except CancelledError:
      raise
  except Exception as error:
      self.app.panic()
      break
```
Should something be done with `error` here? Seems sensible to pass that error to `self.app.panic()` to make it clearer what the underlying issue is. Or at least log it?
