### ISSUE TITLE
Textual does not play nicely with tqdm

### ISSUE THREAD

**Issue by alexiri** [Textualize/textual#2878]
I'm trying to develop a Textual interface for some libraries that use [`tqdm`](https://github.com/tqdm/tqdm) to display a progress bar while loading some data at startup. The progress bar can't be disabled, and it's making the Textual app crash.

Here's a minimal example that demonstrates the issue:

```python
from textual.app import App
from tqdm import tqdm

class OtherClass:
    def __init__(self):
        for i in tqdm(range(10000)):
            pass

class MyApp(App):
    def on_mount(self) -> None:
        self.other = OtherClass()

if __name__ == "__main__":
    app = MyApp()
    app.run()
```

And here's the crash:
```
AttributeError: 'NoneType' object has no attribute 'write'
Exception ignored in: <function tqdm.__del__ at 0x7fd916532d40>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/tqdm/std.py", line 1145, in __del__
    self.close()
  File "/usr/local/lib/python3.10/site-packages/tqdm/std.py", line 1274, in close
    if self.last_print_t < self.start_t + self.delay:
AttributeError: 'tqdm' object has no attribute 'last_print_t'
```

I wouldn't mind so much not being able to see the progress bar, but the app really shouldn't crash.

**Comment by alexiri** [comment]
Fixed by #2880.
