### ISSUE TITLE
Previews from command line no longer work

### ISSUE THREAD

**Issue by labo-China** [Textualize/textual#2944]
Please give a brief but clear explanation of the issue. If you can, include a complete working example that demonstrates the bug. **Check it can run without modifications.**

When launching previews from command line (e.g. calling `textual easing`) , it ends up raising exceptions as following:
> Traceback (most recent call last):
  File "/home/labo/prog/NCSbox/venv/bin/textual", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/labo/prog/NCSbox/venv/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/labo/prog/NCSbox/venv/lib/python3.11/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/labo/prog/NCSbox/venv/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/labo/prog/NCSbox/venv/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/labo/prog/NCSbox/venv/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/labo/prog/NCSbox/venv/lib/python3.11/site-packages/textual_dev/cli.py", line 109, in easing
    from textual.cli.previews import easing
ModuleNotFoundError: No module named 'textual.cli'

From exception prompts we can know that this is due to misplacement of files in refactoring dev tools, which means `textual-dev/previews` should be placed in `textual/cli/previews`. After moving files mannually, everything works fine.

I don`t know whether the preview feature should be preserved in textual or move into textual-dev. I would like to create a PR to fix it if I know where it should be.

**Comment by labo-China** [comment]
By the way, the `BORDER` attribute in constants.py is also missing when running `textual borders` or `textual easing`

**Comment by TomJGooding** [comment]
What version of `textual` and `textual-dev` are you running? It looks like this should already have been moved a few weeks ago.
