### ISSUE TITLE
on() can't match a worker's name

### ISSUE THREAD

**Issue by AstraLuma** [Textualize/textual#3057]
```
class MyScreen(Screen)
    def on_screen_resume(self, event):
        self.search_for_devices()

    @on(Worker.StateChanged, name='ble-scanner')
    def do_worker_change(self, event: Worker.StateChanged):
        if event.state == WorkerState.CANCELLED:
            self.search_for_devices()

    @work(name='ble-scanner', exclusive=True)
    async def search_for_devices(self):
        ...  # Lots of important stuff happens here
```

```
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/home/astraluma/src/pixels-dice/nat20/pixelize/__init__.py", line 103, in <module>
    class DiceBagScreen(Screen):
  File "/home/astraluma/src/pixels-dice/nat20/pixelize/__init__.py", line 112, in DiceBagScreen
    @on(Worker.StateChanged, name='ble-scanner')
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/astraluma/.cache/pypoetry/virtualenvs/nat20-_QmQP8Ap-py3.11/lib/python3.11/site-packages/textual/_on.py", line 73, in on
    raise OnDecoratorError(
textual._on.OnDecoratorError: The attribute 'name' can't be matched; have you added it to StateChanged.ALLOW_SELECTOR_MATCH?
```

**Comment by AstraLuma** [comment]
While this isn't a bug in the strictest sense, it does feel like a UX blemish.

**Comment by willmcgugan** [comment]
I can see why you would want that. And why you might expect it to work. But the `on` decorator matches widgets against CSS selectors, and not arbitrary attributes of the message.

It's not much additional effort to implement a dispatch mechanism inside your state changed handler.

Closing this as a wontfix for now, but I'm open to suggests re what Textual could to to simplify that.

https://label.dev/wontfix/

**Comment by AstraLuma** [comment]
I guess I should reread the messages guide, didn't realize their were two classes of messages.
