### ISSUE TITLE
app hangs when pasting emoji from clipboard to an Input widget

### ISSUE THREAD

**Issue by HubertReX** [Textualize/textual#3178]
Although Input widgets display emojis correctly when a value is set in code (I mean actual emoji like 😊not :smiling_face_with_smiling_eyes:), the whole app hangs when trying to paste emoji from the clipboard on Windows 10.

As a sample code, one can use even this first example:
[Input - Textual](https://textual.textualize.io/widgets/input/#__tabbed_1_2)
Then copy an emoji to the clipboard and then try to paste it (either Ctr+V or Ctrl+Shift+V)
For me, the main app hangs and the respective python process needs to be terminated. The textual console continues to work. 

Here is the output from the textual console:
```
───────────── Client '127.0.0.1' connected ────────────────────────────────────────────────────
[09:56:30] PRINT                                                                                                                                                                                      app.py:1102
Exception in thread Thread-1:
[09:56:30] PRINT                                                                                                                                                                                      app.py:1102
Traceback (most recent call last):
[09:56:30] PRINT                                                                                                                                                                                      app.py:1102
  File "c:\Users\user\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
[09:56:30] PRINT                                                                                                                                                                                      app.py:1102
    self.run()
[09:56:30] PRINT                                                                                                                                                                                      app.py:1102
  File "C:\Projekty\RPG\.py311_env\Lib\site-packages\textual\drivers\_writer_thread.py", line 60, in run
[09:56:30] PRINT                                                                                                                                                                                      app.py:1102
    write(text)
[09:56:30] PRINT                                                                                                                                                                                      app.py:1102
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 423-424: surrogates not allowed


```
I could reproduce this on Win10 in Windows Terminal 1.17 using PowerShell 7. Works fine on Ubuntu 22.
When run using PowerShell, but not inside Windows Terminal, nothing is pasted, but at least the app continues to work. Still, this is useless since emojis do not work in PS without WT.

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.33.0 |
| Rich    | 13.5.2 |

## Python

| Name           | Value                                         |
|----------------|-----------------------------------------------|
| Version        | 3.11.4                                        |
| Implementation | CPython                                       |
| Compiler       | MSC v.1934 64 bit (AMD64)                     |
| Executable     | C:\Projekty\RPG\\.py311_env\Scripts\python.exe |

## Operating System

| Name    | Value      |
|---------|------------|
| System  | Windows    |
| Release | 10         |
| Version | 10.0.19044 |

## Terminal

| Name                 | Value            |
|----------------------|------------------|
| Terminal Application | Windows Terminal |
| TERM                 | *Not set*        |
| COLORTERM            | *Not set*        |
| FORCE_COLOR          | *Not set*        |
| NO_COLOR             | *Not set*        |

## Rich Console options

| Name           | Value                |
|----------------|----------------------|
| size           | width=209, height=52 |
| legacy_windows | False                |
| min_width      | 1                    |
| max_width      | 209                  |
| is_terminal    | True                 |
| encoding       | utf-8                |
| max_height     | 52                   |
| justify        | None                 |
| overflow       | None                 |
| no_wrap        | False                |
| highlight      | None                 |
| markup         | None                 |
| height         | None                 |

**Comment by HubertReX** [comment]
btw, this autogenerated comment needs fixing - the link should read:
https://textual.textualize.io/how-to/center-things/
and not:
https://textual.textualize.io/FAQ/#how-do-i-center-a-widget-in-a-screen

**Comment by davep** [comment]
@HubertReX The auto-generated link is correct, pointing to the FAQ; the other link is the HOWTO, which is far more comprehensive. The reason the FAQ link is broken at the moment is we're "between FAQs" (it used to be in the repo, it's [moving to the docs on website](https://github.com/Textualize/textual/pull/3129), we've just not published the updated version of the docs yet).

**Comment by HubertReX** [comment]
@davep dot it! No problem 👌

**Comment by willmcgugan** [comment]
FAQ links are fixed now...

**Comment by davep** [comment]
Just to confirm: I see the same issue with Windows Terminal 1.17.11461.0 on Windows 11 too.

**Comment by davep** [comment]
Grabbing this to at least investigate further. This might actually have a bit of an overlap with an issue with the default binding we've chosen for the command palette (I discovered the problem while testing it on Windows, as mentioned above). So wanting to get to the bottom of the that problem, I'm grabbing this for the moment too with a view to documenting what's going on (and perhaps, if it's obvious, a fix).

**Comment by davep** [comment]
Keeping an eye out for this while looking at the other Windows drive keyboard issues, this doesn't seem related at all.

---

Looking at it standalone now, and picking 😉 as the test emoji to paste in; when the paste happens the following keyboard events come through into the Windows driver:

| UnicodeChar | AsciiChar | bKeyDown | wRepeatCount | wVirtualKeyCode | wVirtualScanCode | dwControlKeyState |
| -- | -- | -- | -- | -- | -- | -- | 
| '\x00'| b'\x00' | 1 | 1 | 17 | 29 | 8 |
| '\x1b'| b'\x1b' | 1 | 1 | 0 | 0 | 0 |
| '['| b'[' | 1 | 1 | 0 | 0 | 0 |
| '2'| b'2' | 1 | 1 | 0 | 0 | 0 |
| '0'| b'0' | 1 | 1 | 0 | 0 | 0 |
| '0'| b'0' | 1 | 1 | 0 | 0 | 0 |
| '~'| b'~' | 1 | 1 | 0 | 0 | 0 |
| '\ud83d'| b'=' | 1 | 1 | 0 | 0 | 0 |
| '\ude09'| b'\t' | 1 | 1 | 0 | 0 | 0 |
| '\x1b'| b'\x1b' | 1 | 1 | 0 | 0 | 0 |
| '['| b'[' | 1 | 1 | 0 | 0 | 0 |
| '2'| b'2' | 1 | 1 | 0 | 0 | 0 |
| '0'| b'0' | 1 | 1 | 0 | 0 | 0 |
| '1'| b'1' | 1 | 1 | 0 | 0 | 0 |
| '~'| b'~' | 1 | 1 | 0 | 0 | 0 |

The resulting keys collection being:

```python
['\x1b', '[', '2', '0', '0', '~', '\ud83d', '\ude09', '\x1b', '[', '2', '0', '1', '~']
```

`'\x1b', '[', '2', '0', '0', '~'` is the start of bracketed paste, `'\x1b', '[', '2', '0', '1', '~'` the end.

This means the emoji itself is coming through as `'\ud83d', '\ude09'`.

Compare with:

```python
>>> "😉".encode()
b'\xf0\x9f\x98\x89'
```

**Comment by davep** [comment]
My suspicion is that something akin to the above code, needs to happen somewhere around here:

```python
                    # Process keys
                    for event in parser.feed("".join(keys)):
                        self.process_event(event)
```

in the win32 driver.

**Comment by davep** [comment]
Sure enough, if I change the above to:

```python
                    # Process keys
                    for event in parser.feed("".join(keys).encode("utf-16", "surrogatepass").decode("utf-16")):
                        self.process_event(event)
```

it works as expected:

<img width="285" alt="Screenshot 2023-09-13 at 09 17 02" src="https://github.com/Textualize/textual/assets/28237/480b3011-1a52-4913-8235-7d56c1f9a625">

I'd like to check with @darrenburns or @willmcgugan as to the background to this -- the finer points of dealing with emoji and the like really isn't my area of confident knowledge, but it does look like something akin to this is needed in the wind32 driver.

**Comment by willmcgugan** [comment]
This may be the fix. I don't know why Windows encodes emoji as surrogates. If you could find a reference to it in the win32 docs that would be great, but otherwise lets go with this.

@davep I guess this is only required for Windows, so maybe there should be a conditional in there.

**Comment by davep** [comment]
@willmcgugan The change in #3290 is only in `drivers/win32.py` anyway, so that is only for Windows, right?

**Comment by willmcgugan** [comment]
Ah, in that case no need for the conditional.
