### ISSUE TITLE
CancelledError stack trace in terminal after quitting app with Ctrl+C

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#4629]
I just quit my app using Ctrl+C and got the stack trace below. Not seen this before.

<details><summary>Details</summary>
<pre>
Traceback (most recent call last):
  File "/Users/darrenburns/Code/posting/.venv/bin/posting", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/darrenburns/Code/posting/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/darrenburns/Code/posting/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/darrenburns/Code/posting/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/darrenburns/Code/posting/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/darrenburns/Code/posting/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/darrenburns/Code/posting/src/posting/__main__.py", line 34, in default
    app.run()
  File "/Users/darrenburns/Code/posting/.venv/lib/python3.11/site-packages/textual/app.py", line 1611, in run
    asyncio.run(run_app())
  File "/Users/darrenburns/.rye/py/cpython@3.11.7/install/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/darrenburns/.rye/py/cpython@3.11.7/install/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/darrenburns/.rye/py/cpython@3.11.7/install/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/darrenburns/Code/posting/.venv/lib/python3.11/site-packages/textual/app.py", line 1597, in run_app
    await self.run_async(
  File "/Users/darrenburns/Code/posting/.venv/lib/python3.11/site-packages/textual/app.py", line 1563, in run_async
    await app._shutdown()
  File "/Users/darrenburns/Code/posting/.venv/lib/python3.11/site-packages/textual/app.py", line 2778, in _shutdown
    await self._close_all()
  File "/Users/darrenburns/Code/posting/.venv/lib/python3.11/site-packages/textual/app.py", line 2758, in _close_all
    await self._prune_node(stack_screen)
  File "/Users/darrenburns/Code/posting/.venv/lib/python3.11/site-packages/textual/app.py", line 3393, in _prune_node
    await root._close_messages(wait=True)
  File "/Users/darrenburns/Code/posting/.venv/lib/python3.11/site-packages/textual/message_pump.py", line 484, in _close_messages
    await Timer._stop_all(self._timers)
  File "/Users/darrenburns/Code/posting/.venv/lib/python3.11/site-packages/textual/timer.py", line 123, in _stop_all
    await gather(*[stop_timer(timer) for timer in list(timers)])
  File "/Users/darrenburns/Code/posting/.venv/lib/python3.11/site-packages/textual/timer.py", line 121, in stop_timer
    await timer._task
  File "/Users/darrenburns/Code/posting/.venv/lib/python3.11/site-packages/textual/timer.py", line 141, in _run_timer
    async def _run_timer(self) -> None:
asyncio.exceptions.CancelledError
</pre>
</details>

**Comment by willmcgugan** [comment]
Fixed this recently. Try upgrading to 0.66.0
