### ISSUE TITLE
Demo requires httpx

### ISSUE THREAD

**Issue by gbtami** [Textualize/textual#5180]
This happened on Ubuntu 24.04
```
tamas@tami:~$ pip3 install textual --user
Collecting textual
  Using cached textual-0.85.0-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: markdown-it-py>=2.1.0 in /usr/lib/python3/dist-packages (from markdown-it-py[linkify,plugins]>=2.1.0->textual) (3.0.0)
Requirement already satisfied: platformdirs<5,>=3.6.0 in ./.local/lib/python3.12/site-packages (from textual) (4.2.2)
Requirement already satisfied: rich>=13.3.3 in /usr/lib/python3/dist-packages (from textual) (13.7.1)
Requirement already satisfied: typing-extensions<5.0.0,>=4.4.0 in /usr/lib/python3/dist-packages (from textual) (4.10.0)
Requirement already satisfied: mdurl~=0.1 in /usr/lib/python3/dist-packages (from markdown-it-py>=2.1.0->markdown-it-py[linkify,plugins]>=2.1.0->textual) (0.1.2)
Requirement already satisfied: linkify-it-py<3,>=1 in ./.local/lib/python3.12/site-packages (from markdown-it-py[linkify,plugins]>=2.1.0->textual) (2.0.3)
Requirement already satisfied: mdit-py-plugins in ./.local/lib/python3.12/site-packages (from markdown-it-py[linkify,plugins]>=2.1.0->textual) (0.4.2)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/lib/python3/dist-packages (from rich>=13.3.3->textual) (2.17.2)
Requirement already satisfied: uc-micro-py in ./.local/lib/python3.12/site-packages (from linkify-it-py<3,>=1->markdown-it-py[linkify,plugins]>=2.1.0->textual) (1.0.3)
Using cached textual-0.85.0-py3-none-any.whl (614 kB)
Installing collected packages: textual
Successfully installed textual-0.85.0
tamas@tami:~$ python3 -m textual
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/tamas/.local/lib/python3.12/site-packages/textual/__main__.py", line 1, in <module>
    from textual.demo.demo_app import DemoApp
  File "/home/tamas/.local/lib/python3.12/site-packages/textual/demo/demo_app.py", line 3, in <module>
    from textual.demo.home import HomeScreen
  File "/home/tamas/.local/lib/python3.12/site-packages/textual/demo/home.py", line 4, in <module>
    import httpx
ModuleNotFoundError: No module named 'httpx'
tamas@tami:~$ 
```

**Comment by gbtami** [comment]
Maybe just mention this in readme Demo section, idk.
