### ISSUE TITLE
Install instructions don't work

### ISSUE THREAD

**Issue by richstokes** [Textualize/textual#676]
Just following the readme..

```
[rich:...opbox/code/test-python-rich]$ pip install textual    
Requirement already satisfied: textual in /Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages (0.1.18)
Requirement already satisfied: typing-extensions<5.0,>=4.0.0 in /Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages (from textual) (4.2.0)
Requirement already satisfied: rich<13.0.0,>=12.3.0 in /Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages (from textual) (12.4.4)
Requirement already satisfied: pygments<3.0.0,>=2.6.0 in /Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages (from rich<13.0.0,>=12.3.0->textual) (2.12.0)
Requirement already satisfied: commonmark<0.10.0,>=0.9.0 in /Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages (from rich<13.0.0,>=12.3.0->textual) (0.9.1)
WARNING: You are using pip version 21.0; however, version 22.2.2 is available.
You should consider upgrading via the '/Users/rich/.pyenv/versions/3.8.7/bin/python3.8 -m pip install --upgrade pip' command.
[rich:...opbox/code/test-python-rich]$ python -m textual.app  

Traceback (most recent call last):
  File "/Users/rich/.pyenv/versions/3.8.7/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/rich/.pyenv/versions/3.8.7/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/Users/rich/Dropbox/code/test-python-rich/textual.py", line 1, in <module>
    from textual.app import App
ModuleNotFoundError: No module named 'textual.app'; 'textual' is not a package
```

```
[rich:...opbox/code/test-python-rich]$ python -V
Python 3.8.7
[rich:...opbox/code/test-python-rich]$ pip -V
pip 21.0 from /Users/rich/.pyenv/versions/3.8.7/lib/python3.8/site-packages/pip (python 3.8)
```

**Comment by richstokes** [comment]
nvm im being dumb

**Comment by NerdKnight66** [comment]
> nvm im being dumb

What did you do wrong? I'm encountering this issue too

**Comment by richstokes** [comment]
@NerdKnight66 I think I had named my file `textual.py`, which was conflicting when trying to import the actual module

**Comment by NerdKnight66** [comment]
Yup, that was the problem. Maybe they should put a warning in the README about that

**Comment by richstokes** [comment]
I’m fairness, that’s a generic python behavior. Not specific to this code.

**Comment by NerdKnight66** [comment]
Yeah, it’s definitely on me for being an idiot. I just haven’t encountered it with other packages before. Something to look out for in future though!
