### ISSUE TITLE
Runing textual raise a LookupError

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#752]
### Discussed in https://github.com/Textualize/textual/discussions/750

<div type='discussions-op-text'>

<sup>Originally posted by **lab-do** September  8, 2022</sup>
Trying to run any of the examples gives me this error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\ABDO\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\code\example\.venv\lib\site-packages\textual\drivers\win32.py", line 227, in run
    self.app.log("event monitor thread started")
  File "D:\code\example\.venv\lib\site-packages\textual\__init__.py", line 37, in __call__
    app = active_app.get()
LookupError: <ContextVar name='active_app' at 0x000002252EDC8C70>
```

This is what I'm using in poetry dependencies `textual = {git = "https://github.com/Textualize/textual.git", rev = "css", extras = ["dev"]}`</div>

**Comment by lab-do** [comment]
#753 fixed this issue for me 👌
